db:
  image: postgres
  restart: always
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: squad9
    POSTGRES_DB: gestao_hospitalar

adminer:
    image: adminer
    restart: always
    links:
      - db:db
    ports:
      - 8083:8080
